name: "Publish application using the given parameters"

on:
  workflow_call:
    inputs:
      container_tag:
        required: true
        type: string
      petclinic_root:
        type: string
        default: petclinic

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out branch
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        working-directory: ${{ inputs.petclinic_root }}
        run: chmod +x gradlew
      - name: Build and package application with Gradle
        working-directory: ${{ inputs.petclinic_root }}
        run: ./gradlew bootJar

      - name: Log in to the Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract container metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and publish Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.petclinic_root }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.container_tag }}
          labels: ${{ steps.meta.outputs.labels }}
